// Mock data for development - will be replaced with API calls to MERN backend
import { Technician, Service, Booking, ForumPost, AIDiagnostic } from '@/types';

export const mockTechnicians: Technician[] = [
  {
    id: '1',
    name: 'Suresh Krishnan',
    email: 'suresh@quickfix.com',
    phone: '+91 9847123456',
    role: 'technician',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Suresh',
    location: 'Kochi, Kerala',
    skills: ['electrical', 'appliance'],
    rating: 4.9,
    totalJobs: 250,
    badges: ['super_technician', 'fast_responder', 'highly_rated'],
    verified: true,
    availability: true,
    hourlyRate: 500,
    bio: 'Expert electrician with 10+ years of experience in residential and commercial repairs.',
    experience: 10,
    createdAt: new Date('2020-01-15'),
  },
  {
    id: '2',
    name: 'Lakshmi Menon',
    email: 'lakshmi@quickfix.com',
    phone: '+91 9847654321',
    role: 'technician',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lakshmi',
    location: 'Trivandrum, Kerala',
    skills: ['plumbing', 'hvac'],
    rating: 4.8,
    totalJobs: 180,
    badges: ['highly_rated', 'expert_specialist'],
    verified: true,
    availability: true,
    hourlyRate: 600,
    bio: 'Certified plumber specializing in modern plumbing solutions and water heating systems.',
    experience: 8,
    createdAt: new Date('2020-06-20'),
  },
  {
    id: '3',
    name: 'Arun Kumar',
    email: 'arun@quickfix.com',
    phone: '+91 9847987654',
    role: 'technician',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arun',
    location: 'Kozhikode, Kerala',
    skills: ['carpentry', 'painting'],
    rating: 4.7,
    totalJobs: 150,
    badges: ['fast_responder'],
    verified: true,
    availability: false,
    hourlyRate: 450,
    bio: 'Skilled carpenter and painter with expertise in custom furniture and interior work.',
    experience: 6,
    createdAt: new Date('2021-03-10'),
  },
];

export const mockServices: Service[] = [
  {
    id: '1',
    category: 'electrical',
    name: 'Electrical Repairs',
    description: 'Wiring, switches, outlets, circuit breakers, and more',
    icon: '⚡',
    averagePrice: 800,
    estimatedDuration: '1-2 hours',
  },
  {
    id: '2',
    category: 'plumbing',
    name: 'Plumbing Services',
    description: 'Leaks, pipe repairs, drain cleaning, fixture installation',
    icon: '🔧',
    averagePrice: 1000,
    estimatedDuration: '1-3 hours',
  },
  {
    id: '3',
    category: 'carpentry',
    name: 'Carpentry Work',
    description: 'Furniture repair, door/window fixes, custom woodwork',
    icon: '🪚',
    averagePrice: 1200,
    estimatedDuration: '2-4 hours',
  },
  {
    id: '4',
    category: 'painting',
    name: 'Painting Services',
    description: 'Interior/exterior painting, wall preparation, touch-ups',
    icon: '🎨',
    averagePrice: 2000,
    estimatedDuration: '4-8 hours',
  },
  {
    id: '5',
    category: 'hvac',
    name: 'HVAC Maintenance',
    description: 'AC repair, servicing, installation, duct cleaning',
    icon: '❄️',
    averagePrice: 1500,
    estimatedDuration: '2-3 hours',
  },
  {
    id: '6',
    category: 'appliance',
    name: 'Appliance Repair',
    description: 'Refrigerator, washing machine, microwave, dishwasher repairs',
    icon: '🔌',
    averagePrice: 900,
    estimatedDuration: '1-2 hours',
  },
  {
    id: '7',
    category: 'locksmith',
    name: 'Locksmith Services',
    description: 'Lock installation, key duplication, emergency lockouts',
    icon: '🔑',
    averagePrice: 600,
    estimatedDuration: '30 mins - 1 hour',
  },
  {
    id: '8',
    category: 'cleaning',
    name: 'Deep Cleaning',
    description: 'Home cleaning, carpet cleaning, post-renovation cleanup',
    icon: '🧹',
    averagePrice: 1800,
    estimatedDuration: '3-5 hours',
  },
];

export const mockBookings: Booking[] = [
  {
    id: '1',
    userId: 'user1',
    technicianId: '1',
    serviceCategory: 'electrical',
    description: 'Kitchen outlet not working, need urgent repair',
    status: 'confirmed',
    scheduledDate: new Date('2025-01-25T10:00:00'),
    location: 'Flat 301, Marina Apartments, Kochi',
    estimatedCost: 800,
    photos: [],
    createdAt: new Date('2025-01-20'),
    updatedAt: new Date('2025-01-20'),
  },
  {
    id: '2',
    userId: 'user1',
    technicianId: '2',
    serviceCategory: 'plumbing',
    description: 'Bathroom tap leaking continuously',
    status: 'completed',
    scheduledDate: new Date('2025-01-15T14:00:00'),
    location: 'Flat 301, Marina Apartments, Kochi',
    estimatedCost: 600,
    actualCost: 650,
    rating: 5,
    review: 'Excellent service! Very professional and quick.',
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date('2025-01-15'),
  },
];

export const mockForumPosts: ForumPost[] = [
  {
    id: '1',
    authorId: 'user2',
    authorName: 'Anjali Nair',
    authorRole: 'customer',
    title: 'Best way to prevent pipe issues during monsoon?',
    content: 'Living in Kerala, monsoon brings a lot of water-related issues. What are some preventive measures I can take?',
    category: 'plumbing',
    upvotes: 15,
    comments: [
      {
        id: 'c1',
        postId: '1',
        authorId: '2',
        authorName: 'Lakshmi Menon',
        authorRole: 'technician',
        content: 'Regular drain cleaning before monsoon, ensure proper slope for drainage, and keep gutters clear. Check for any pipe cracks early!',
        upvotes: 20,
        createdAt: new Date('2025-01-18'),
      },
    ],
    createdAt: new Date('2025-01-17'),
  },
  {
    id: '2',
    authorId: '1',
    authorName: 'Suresh Krishnan',
    authorRole: 'technician',
    title: 'DIY Electrical Safety Tips',
    content: 'As an electrician in Kerala, here are my top 5 safety tips when dealing with electrical work at home during monsoon...',
    category: 'electrical',
    upvotes: 45,
    comments: [],
    createdAt: new Date('2025-01-19'),
  },
];

export const mockDiagnostics: AIDiagnostic[] = [
  {
    id: '1',
    userId: 'user1',
    images: ['/placeholder.svg'],
    predictedIssue: 'Faulty Electrical Outlet',
    severity: 'medium',
    estimatedCost: 800,
    requiredCategory: 'electrical',
    confidence: 0.87,
    recommendations: [
      'Replace the damaged outlet immediately',
      'Check for loose wiring connections',
      'Consider upgrading to GFCI outlets for safety',
    ],
    createdAt: new Date('2025-01-20'),
  },
];
